#!/usr/bin/env python3
"""Generate the Phosphor icon block in theme.css from scripts/icons.json.

Usage: scripts/build-icons.py [path-to-phosphor-regular-dir]
The Phosphor SVGs used are copied into assets/phosphor/ so the build is
reproducible without the package. Phosphor Icons are MIT licensed
(https://github.com/phosphor-icons/core).
"""
import json, os, re, shutil, sys, urllib.parse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, "scripts", "icons.json")
VENDOR = os.path.join(ROOT, "assets", "phosphor")
THEME = os.path.join(ROOT, "theme.css")
START = "/* ==== Phosphor icons: generated by scripts/build-icons.py, do not edit ==== */"
END = "/* ==== end Phosphor icons ==== */"

src = sys.argv[1] if len(sys.argv) > 1 else None
mapping = {k: v for k, v in json.load(open(MAP)).items() if not k.startswith("_")}
os.makedirs(VENDOR, exist_ok=True)

rules = []
missing = []
for lucide, phos in sorted(mapping.items()):
    vendored = os.path.join(VENDOR, phos + ".svg")
    if not os.path.exists(vendored):
        if src and os.path.exists(os.path.join(src, phos + ".svg")):
            shutil.copy(os.path.join(src, phos + ".svg"), vendored)
        else:
            missing.append((lucide, phos))
            continue
    svg = open(vendored).read()
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    svg = svg.replace('fill="currentColor"', 'fill="#000"')
    svg = re.sub(r"\s+", " ", svg).strip()
    uri = "data:image/svg+xml," + urllib.parse.quote(svg, safe="/:=,' ").replace(" ", "%20")
    rules.append(
        f'svg.svg-icon.lucide-{lucide} {{ -webkit-mask-image: url("{uri}"); mask-image: url("{uri}"); }}'
    )

block = "\n".join([
    START,
    "/* Each Obsidian icon keeps its <svg> box; the Lucide paths are hidden and a",
    "   Phosphor glyph is masked over it in the current color. */",
    "svg.svg-icon[class*=\"lucide-\"] {",
    "  -webkit-mask-size: contain;",
    "  mask-size: contain;",
    "  -webkit-mask-position: center;",
    "  mask-position: center;",
    "  -webkit-mask-repeat: no-repeat;",
    "  mask-repeat: no-repeat;",
    "}",
    *rules,
    "/* Hide the Lucide paths only for icons that have a Phosphor replacement */",
    ",\n".join(f"svg.svg-icon.lucide-{l} > *" for l in sorted(mapping) if (l, mapping[l]) not in missing) + " {",
    "  display: none;",
    "}",
    ",\n".join(f"svg.svg-icon.lucide-{l}" for l in sorted(mapping) if (l, mapping[l]) not in missing) + " {",
    "  background-color: currentColor;",
    "}",
    END,
])

theme = open(THEME).read()
if START in theme:
    theme = theme[: theme.index(START)] + block + theme[theme.index(END) + len(END):]
else:
    theme = theme.rstrip("\n") + "\n\n" + block + "\n"
open(THEME, "w").write(theme)
print(f"{len(rules)} icons written, {len(missing)} missing")
for m in missing:
    print("  missing:", m)
