#!/usr/bin/env python3
"""Generate the Phosphor icon block in theme.css from scripts/icons.json.

Usage: scripts/build-icons.py [path-to-phosphor-regular-dir]
The Phosphor SVGs used are copied into assets/phosphor/ so the build is
reproducible without the package. Phosphor Icons are MIT licensed
(https://github.com/phosphor-icons/core).
"""
import json, os, re, shutil, sys, urllib.parse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, "scripts", "icons.json")
VENDOR = os.path.join(ROOT, "assets", "phosphor")
THEME = os.path.join(ROOT, "theme.css")
START = "/* ==== Phosphor icons: generated by scripts/build-icons.py, do not edit ==== */"
END = "/* ==== end Phosphor icons ==== */"

src = sys.argv[1] if len(sys.argv) > 1 else None
mapping = {k: v for k, v in json.load(open(MAP)).items() if not k.startswith("_")}
os.makedirs(VENDOR, exist_ok=True)

rules = []
missing = []
by_glyph = {}
for lucide, phos in sorted(mapping.items()):
    vendored = os.path.join(VENDOR, phos + ".svg")
    if not os.path.exists(vendored):
        if src and os.path.exists(os.path.join(src, phos + ".svg")):
            shutil.copy(os.path.join(src, phos + ".svg"), vendored)
        else:
            missing.append((lucide, phos))
            continue
    svg = open(vendored).read()
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    # Masks only read alpha, and SVG paths default to an opaque black fill,
    # so the fill attribute can go. Keep the escaping minimal: only the
    # characters that would break a data URI inside url("...").
    svg = svg.replace(' fill="currentColor"', "")
    svg = re.sub(r"\s+", " ", svg).strip()
    svg = svg.replace('"', "'").replace("<", "%3C").replace(">", "%3E").replace("#", "%23")
    uri = "data:image/svg+xml," + svg
    by_glyph.setdefault(uri, []).append(lucide)

# One rule per unique glyph; several Lucide names can share it. Unprefixed
# mask-image is enough: Obsidian 1.13 ships Chromium 120+ and iOS 15.4+.
for uri, names in by_glyph.items():
    sel = ",".join(f"svg.svg-icon.lucide-{n}" for n in names)
    kids = ",".join(f"svg.svg-icon.lucide-{n}>*" for n in names)
    rules.append(f'{sel}{{background-color:currentColor;mask-image:url("{uri}")}}{kids}{{display:none}}')

block = "\n".join([
    START,
    "/* Each Obsidian icon keeps its <svg> box; the Lucide paths are hidden and a",
    "   Phosphor glyph is masked over it in the current color. */",
    "svg.svg-icon[class*=\"lucide-\"] {",
    "  mask-size: contain;",
    "  mask-position: center;",
    "  mask-repeat: no-repeat;",
    "}",
    *rules,
    END,
])

theme = open(THEME).read()
if START in theme:
    theme = theme[: theme.index(START)] + block + theme[theme.index(END) + len(END):]
else:
    theme = theme.rstrip("\n") + "\n\n" + block + "\n"
open(THEME, "w").write(theme)
print(f"{len(rules)} icons written, {len(missing)} missing")
for m in missing:
    print("  missing:", m)
